// domElements.js
// Centralized export of all DOM elements for easier management

export const elements = {
    loadingOverlay: document.getElementById('loadingOverlay'),
    notificationContainer: document.getElementById('notificationContainer'),

    themeSelect: document.getElementById('themeSelect'),
    apiKeyInput: document.getElementById('apiKeyInput'),
    testApiBtn: document.getElementById('testApiBtn'),
    settingsBtn: document.getElementById('settingsBtn'),
    helpBtn: document.getElementById('helpBtn'),

    dropZone: document.getElementById('dropZone'),
    fileInput: document.getElementById('fileInput'),
    dataTextarea: document.getElementById('dataTextarea'),
    delimiterSelect: document.getElementById('delimiterSelect'),
    hasHeadersCheckbox: document.getElementById('hasHeadersCheckbox'),
    autoProcessCheckbox: document.getElementById('autoProcessCheckbox'),
    processDataBtn: document.getElementById('processDataBtn'),
    clearAllBtn: document.getElementById('clearAllBtn'),

    rowCountSpan: document.getElementById('rowCount'),
    columnCountSpan: document.getElementById('columnCount'),
    numericColumnsSpan: document.getElementById('numericColumns'),
    missingValuesSpan: document.getElementById('missingValues'),
    dataQualityDiv: document.getElementById('dataQuality'),
    qualityIndicatorsDiv: document.getElementById('qualityIndicators'),
    aiCleaningSuggestions: document.getElementById('aiCleaningSuggestions'),
    cleaningSuggestionsList: document.getElementById('cleaningSuggestionsList'),
    dataPreviewTable: document.getElementById('dataPreviewTable'),
    tableHead: document.getElementById('tableHead'),
    tableBody: document.getElementById('tableBody'),
    noDataMessage: document.getElementById('noDataMessage'),

    exportChartBtn: document.getElementById('exportChartBtn'),
    chartTypeSelect: document.getElementById('chartTypeSelect'),
    xAxisSelect: document.getElementById('xAxisSelect'),
    yAxisSelect: document.getElementById('yAxisSelect'),
    chartTitleInput: document.getElementById('chartTitleInput'),
    colorSchemeSelect: document.getElementById('colorSchemeSelect'),
    updateChartBtn: document.getElementById('updateChartBtn'),
    mainChartCanvas: document.getElementById('mainChart'),
    heatmapContainer: document.getElementById('heatmapContainer'),
    chartPlaceholder: document.getElementById('chartPlaceholder'),

    apiStatusIndicator: document.querySelector('#apiStatus .status-indicator'),
    apiStatusText: document.querySelector('#apiStatus .status-text'),
    analysisTypeSelect: document.getElementById('analysisTypeSelect'),
    toneOfVoiceSelect: document.getElementById('toneOfVoiceSelect'),
    customQuestionGroup: document.getElementById('customQuestionGroup'),
    customQuestionTextarea: document.getElementById('customQuestion'),
    analyzeBtn: document.getElementById('analyzeBtn'),
    generateStoryBtn: document.getElementById('generateStoryBtn'),
    exportAnalysisBtn: document.getElementById('exportAnalysisBtn'),
    aiResponseArea: document.getElementById('aiResponseArea'),
    responseTitle: document.getElementById('responseTitle'),
    aiResponseContent: document.getElementById('aiResponse'),
    copyResponseBtn: document.getElementById('copyResponseBtn'),
    regenerateBtn: document.getElementById('regenerateBtn'),

    exportCsvBtn: document.getElementById('exportCsvBtn'),
    exportJsonBtn: document.getElementById('exportJsonBtn'),
    exportExcelBtn: document.getElementById('exportExcelBtn'),
    exportPngBtn: document.getElementById('exportPngBtn'),
    exportSvgBtn: document.getElementById('exportSvgBtn'),
    exportPdfBtn: document.getElementById('exportPdfBtn'),
    exportReportBtn: document.getElementById('exportReportBtn'),
    shareReportBtn: document.getElementById('shareReportBtn'),

    settingsModal: document.getElementById('settingsModal'),
    closeSettingsModalBtn: document.getElementById('closeSettingsModal'),
    settingAutoProcessCheckbox: document.getElementById('settingAutoProcess'),
    settingValidateDataCheckbox: document.getElementById('settingValidateData'),
    settingAnimateChartsCheckbox: document.getElementById('settingAnimateCharts'),
    settingHighContrastCheckbox: document.getElementById('settingHighContrast'),
    settingAutoAnalyzeCheckbox: document.getElementById('settingAutoAnalyze'),
    settingMaxTokensSelect: document.getElementById('settingMaxTokens'),
    settingNotificationsCheckbox: document.getElementById('settingNotifications'),
    settingCompactModeCheckbox: document.getElementById('settingCompactMode'),
    resetSettingsBtn: document.getElementById('resetSettingsBtn'),
    saveSettingsBtn: document.getElementById('saveSettingsBtn'),

    helpModal: document.getElementById('helpModal'),
    closeHelpModalBtn: document.getElementById('closeHelpModal'),
    helpTabs: document.querySelectorAll('.help-tab'),
    helpContents: document.querySelectorAll('.help-content'),

    progressModal: document.getElementById('progressModal'),
    progressTitle: document.getElementById('progressTitle'),
    progressMessage: document.getElementById('progressMessage'),
    progressFill: document.getElementById('progressFill'),
};
